[build]
  command = "pnpm install --ignore-scripts=false && pnpm add sharp@0.34.3 --force && gatsby build --verbose"
  publish = "public"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[build.environment]
  NODE_VERSION = "18.20.4"
  NPM_FLAGS = "--legacy-peer-deps"
  SHARP_IGNORE_GLOBAL_LIBVIPS = "1"
  GATSBY_CPU_COUNT = "2"
  NODE_OPTIONS = "--max-old-space-size=4096"
  SHARP_DIST_BASE_URL = "https://github.com/lovell/sharp-libvips/releases/download/v8.15.0/"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_NPM = "false"
  NETLIFY_USE_PNPM = "false"

[[build.processing]]
  skip_processing = false
