[build]
  command = "pnpm install --ignore-scripts=false && gatsby build --verbose"
  publish = "public"

[build.environment]
  NODE_VERSION = "18.20.4"
  NPM_FLAGS = "--legacy-peer-deps"
  SHARP_IGNORE_GLOBAL_LIBVIPS = "1"
  GATSBY_CPU_COUNT = "2"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[build.processing]]
  skip_processing = false
