[build]
  command = "pnpm install --ignore-scripts=false && gatsby build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18.20.4"
  NPM_FLAGS = "--legacy-peer-deps"
  SHARP_IGNORE_GLOBAL_LIBVIPS = "1"

[[build.processing]]
  skip_processing = false
